#########################################################
#                  RunRule Settings                     #
#########################################################


boardModel:
 SIMULATION 

enableMPCX:
 false 

maxfileName:
 LinearRegression

mainClass:
 linearregression.LinearRegressionManager

remoteExecution:
 false
